feat: Customize max altitude for settings panel
skylarkdrones/android-sdk-v5-uxsdk pull request #1
Opened 2024-12-23 18:43 UTC by bk99sd

Allow customizing the max altitude in the settings panel while using the library

2025-01-03 04:35 UTC, shantanu-skylark requested changes

2025-01-06 05:45 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/fragment/FlycMenuFragment.java
> +    public void onResume() {
Doing it inside the `onViewCreated()` will result in a crash as the EditorCell view object for the height cell thorws a null pointer exeception.

2025-01-06 12:36 UTC, shantanu-skylark commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/fragment/FlycMenuFragment.java
[issue:medium]

The `RTH Altitude` and `Max Altitude` are set out of range by default.

![image](https://github.com/user-attachments/assets/2a7d2061-5342-4490-8c74-5c4c136884f5)

2025-01-08 10:52 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelWidget.java
> +    private int maxAltitude = 120;
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/cded80cc746b6e7db65caec2a46be5a2e5c6b438

2025-01-08 10:52 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/ui/SettingMenuFragment.java
> +    public static SettingMenuFragment newInstance(
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/5b349760cfeecf6797a52505facb9d5bb75e8ebc

2025-01-08 11:40 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/fragment/FlycMenuFragment.java
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/4c526d5c17f358d6a4182a39f9037d78a7d9ee63

2025-01-21 07:15 UTC, shantanu-skylark requested changes

2025-01-21 07:15 UTC, shantanu-skylark commented
Testing passes.

2025-01-23 06:59 UTC, thesohelshaikh commented
Requires a rebase

2025-01-23 07:35 UTC, thesohelshaikh requested changes

2025-01-23 07:35 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/res/values/attrs.xml
> +    <!--  Max altitude & distance customization  -->
Let's document the unit being used here

2025-01-23 07:35 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/ui/SettingMenuFragment.java
> +    public static final int DEFAULT_MIN_DISTANCE = 15;
Not sure why this is different from DJI Pilot 2, the value there is 20 meters

2025-01-23 07:35 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/ui/SettingMenuFragment.java
> +    public static final int DEFAULT_MAX_DISTANCE = 8000;
Shouldn't `max_distance` be 1000 meters

2025-01-23 07:35 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/ui/SettingMenuFragment.java
> +    public static final int DEFAULT_MAX_DISTANCE = 8000;
Does it make sense to move these constants to respective widget classes?

2025-01-23 07:35 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
Incorrect message is shown when value is smaller than min limit

![image](https://github.com/user-attachments/assets/0f65c92d-f83e-47ce-abe0-03d9c0710fa3)

2025-01-23 07:35 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelWidget.java
> +        setMasterFragmentData();
We are recreating fragments here?

2025-01-23 07:35 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/res/layout/uxsdk_setting_menu_aircraft_layout.xml
> +        android:id="@+id/layoutDistanceWidget"
Are we using this?

2025-01-30 05:50 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/ui/SettingMenuFragment.java
> +    public static final int DEFAULT_MAX_DISTANCE = 8000;
Not valid for `SettingMenuFragment` as these are now only confined to `SettingPanelWidget`

2025-01-30 05:51 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/ui/SettingMenuFragment.java
> +    public static final int DEFAULT_MIN_DISTANCE = 15;
Updated in the latest commits

2025-01-30 05:51 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/ui/SettingMenuFragment.java
> +    public static final int DEFAULT_MAX_DISTANCE = 8000;
Updated in the latest commits

2025-01-30 05:52 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelWidget.java
> +        setMasterFragmentData();
Not valid anymore the logic has been changed

2025-01-30 05:52 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/res/layout/uxsdk_setting_menu_aircraft_layout.xml
> +        android:id="@+id/layoutDistanceWidget"
Yes this is needed

2025-01-30 05:55 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
It's because DJI widget has a common check for range (which I also prefer) and it uses a common message for it, shall we modify the message to "Setting failed, outside allowed range" ?

2025-01-30 05:57 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/res/values/attrs.xml
> +    <!--  Max altitude & distance customization  -->
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/7913208a03f9c2d36f4c37139230ff639ae3c77e

2025-01-30 06:07 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/ui/setting/fragment/FlycMenuFragment.java
> +            maxDistanceCell.setTips(minDistance + "~" + maxDistance + "m");
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/fe96941c86c62e91e50dabf037a27c1ae9fb310f

2025-01-30 11:26 UTC, shantanu-skylark requested changes

2025-01-30 11:26 UTC, shantanu-skylark commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidgetModel.java
> +    private final DataProcessor<Boolean> distanceLimitEnableDataProcessor = DataProcessor.create(true);
Is this required?

2025-01-30 11:36 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidgetModel.java
> +    private final DataProcessor<Boolean> distanceLimitEnableDataProcessor = DataProcessor.create(true);
Not needed, pushed test code by mistake, updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/f35524efbbef28ce2836175bfb833c9e1d1977bb

2025-01-31 05:18 UTC, bk99sd commented on android-sdk-v5-sample/src/main/java/dji/sampleV5/aircraft/DJIMainActivity.kt
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/2500d79a038c377e9e3334d7ff231cbecfb98d3e

2025-01-31 05:18 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelState.kt
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/0eae8a98d5412422d4e89a236bb18f87cd977d2f

2025-01-31 05:18 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelState.kt
> +    private var maxDistance = 0
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/0eae8a98d5412422d4e89a236bb18f87cd977d2f

2025-01-31 05:18 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelWidget.java
> +        mFragments.add(
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/ea0912293ada1b9f84678535927a5a526f10ab3b

2025-02-05 10:03 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/aac1b552886a17ee7978912371e8495484be5e19

2025-02-06 07:41 UTC, shantanu-skylark commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
[issue:low]

Noticing the "Saved successfully" toast when we open the free flight screen every time.

2025-02-06 07:51 UTC, shantanu-skylark commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
[issue:low]

The set altitude or distance is overriden to 120 or 1000 m respectively when the app is reopened.

Steps to reproduce:
- In DJI Pilot 2, set the max and RTH altitude to 60m and distance to 600m.
- Close the app.
- Open the DMO.
- Notice the value which were set in DJI Pilot 2 are overriden to 120m altitude and 1000m distance.

This doesn't happen when the DMO and DJI Pilot 2 are opened side-by-side.

2025-02-06 08:19 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/8d9868515f7d555892e226384d4c9c7b64eda9d2

2025-02-06 08:19 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
This commit https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/8d9868515f7d555892e226384d4c9c7b64eda9d2 should fix it as well

2025-02-06 09:11 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +            });
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/9869e030038ae1bc796e62c2336871806e011b97

2025-02-06 12:14 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
Was the certification flag set to true before you had pushed to maven local?

2025-02-06 12:19 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
In Pilot 2 you can disable it but when you come back to the DMO app your limits will be respected

2025-02-06 14:28 UTC, shantanu-skylark approved these changes

2025-02-10 09:09 UTC, thesohelshaikh requested changes

2025-02-10 09:09 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        widgetModel.setDistanceLimitEnabled(true).subscribe();
Will this not be take care by `onValueChanged()`?

2025-02-10 09:09 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +    }
Why do we have two variables tracking the same state?

2025-02-10 09:09 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        widgetModel.setDistanceLimitEnabled(true).subscribe();
Why are we subscribing here?

2025-02-10 09:09 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        if (!isCertificationBuild) {
Not required if the widget is disabled?

2025-02-10 09:09 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +    private void updateDistanceLimitEnable(Boolean isChecked) {
This function has been moved, should not be part of the diff

2025-02-10 09:09 UTC, thesohelshaikh commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        mMaxRadiusEditorCell.setValue(Math.min(maxRadius, integer));
Buffer should be applied when setting the value as we will never end up breaching it

2025-02-10 09:15 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        setupLimits();
Calling it `initView()` doesn't work

2025-02-10 11:43 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        mMaxRadiusEditorCell.setValue(Math.min(maxRadius, integer));
Not needed now we set the maxRadius with the bufferedValue now

2025-02-10 11:43 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +    private void updateDistanceLimitEnable(Boolean isChecked) {
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/4e5d60b0f115b58fb0b04960ca62cc8bf7d5f30f

2025-02-10 11:43 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        if (!isCertificationBuild) {
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/adc6dca11249dad42e846d7631a1d2c46f70bc2c

2025-02-10 11:43 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        widgetModel.setDistanceLimitEnabled(true).subscribe();
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/adc6dca11249dad42e846d7631a1d2c46f70bc2c

2025-02-10 11:44 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +    }
Clarified using a comment https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/adc6dca11249dad42e846d7631a1d2c46f70bc2c

2025-02-10 11:44 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        widgetModel.setDistanceLimitEnabled(true).subscribe();
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/adc6dca11249dad42e846d7631a1d2c46f70bc2c

2025-02-10 11:44 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +    private static final int maxDistance = 1000;
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/adc6dca11249dad42e846d7631a1d2c46f70bc2c

2025-02-10 11:44 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidgetModel.java
> +    private final DataProcessor<Integer> distanceLimitDataProcessor = DataProcessor.create(500);
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/adc6dca11249dad42e846d7631a1d2c46f70bc2c

2025-02-10 11:44 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +            setupDistanceLimit();
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/11551872960793215f7814b2eecfab839d0820e3

2025-02-10 11:54 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        setupLimits();
Uploading ss_contructor_after_initView.mp4…

2025-02-10 11:56 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +        if (isCertificationBuild && integer > bufferAltitudeLimitMeters) {
These if checks are required to reset the initial value, without opening the settings panel. Also the code to modify altitude and distance limits in main app only does it when the drone is flying. (i.e. location is updating)

2025-02-11 06:41 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/flight/flightparam/DistanceLimitWidget.java
> +    }
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1/commits/db6938544338e5f437802aeefe9874972abc8f41

2025-02-13 12:44 UTC, thesohelshaikh approved these changes

2025-02-13 12:44 UTC, merged