feat: Customize max distance for settings panel
skylarkdrones/android-sdk-v5-uxsdk pull request #2
Opened 2024-12-27 15:10 UTC by bk99sd

Allow customizing the max distance in the settings panel while using the library

2025-01-06 11:56 UTC, shantanu-skylark requested changes

2025-01-06 11:56 UTC, shantanu-skylark commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelWidget.java
> +    private int maxDisance = 8000;
[refactor:low]

Let's extract the relevant numbers to constants

2025-01-08 11:44 UTC, bk99sd commented on android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/widget/setting/SettingPanelWidget.java
> +    private int maxDisance = 8000;
Updated https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/2/commits/fa792cdfeec38113d3c0e7616f248476258d72f6

2025-02-05 06:02 UTC, thesohelshaikh commented
Superseeded by https://github.com/skylarkdrones/android-sdk-v5-uxsdk/pull/1

2025-02-05 06:02 UTC, closed without merging